services:
  - type: web
    name: jhawk-flight-schedule
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: INCHEON_API_KEY
        sync: false
